 class VarArgDemo {
	public static void main(String[]args){

		VarArgDemo ref = new VarArgDemo();

		System.out.println("Addition of num is:" + ref.sum(99));
		System.out.println("Addition of num is:" + ref.sum(99,3,5));
		System.out.println("Addition of num is:" + ref.sum(99,6,8,9,9));
		System.out.println("Addition of num is:" + ref.sum());
}

		int sum(int...values) {
     int sum=0;
     for (int i:values){
      sum=sum+i;
}
        return sum;
}
}
